title: "Projekt_dom"
author:
  - Magda Chyla
date: "r format(Sys.Date())"
output:
  bookdown::html_document2:
  code_folding: show
keep_md: yes
toc: TRUE
toc_float: TRUE
toc_depth: 6
fig_caption: yes
bibliography: BalticPhotoperiod.bib
csl: plos-one.csl
editor_options: 
  markdown: 
  wrap: 72


```{r load libraries, warning = FALSE, echo=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(data.table)
library(googledrive)
library(googlesheets4)
library(ggforce)
```


```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Figs/')
```






```{r, Warning = FALSE, Echo = FALSE}
gs4_deauth()
# this is the URL or ID of a Sheet readable by anyone (with a link)
CultureCatalog <- read_sheet("https://docs.google.com/spreadsheets/d/1ZXpwR7Gfto-uRzVdXzMpQF4frbrvMLH_IyLqonFZRSw/edit#gid=0")
```

```{r}
circles <- data.frame(x0 = 3, y0 = 3, r = 1)
# circles <- data.frame(x0 = rep(1:3, 3),y0 = rep(1:3, each = 3),r = seq(0.1, 1, length.out = 9))

ggplot() +
  geom_circle(aes(x0 = x0, y0 = y0, r = r), fill = "darkgreen", data = circles)
```





```{r}
angle=pi/3
x <- c(0,0.5,0.5*cos(angle),0)
y <- c(0,0,sin(angle),0)
y1 <- c(0,0,-sin(angle),0)

plot(-1:1,-1:1,type='n')
polygon(x=x,y=y,col='red')      ## you can replace polygon by lines here 
polygon(x=x,y=y1,col='green')
```


```{r}
library(plotrix)
x = runif(100, -1, 1)
y = runif(100, -1, 1)
plot(x, y, asp = 1, xlim = c(-1, 1), ylim = c(-1, 1))
draw.circle(0, 0, 1, nv = 5)
```



```{r}

# Create a data frame with circle coordinates
circle <- data.frame(
  x = cos(seq(0, 2 * pi, length.out = 100)),
  y = sin(seq(0, 2 * pi, length.out = 100))
)

# Plot the circle
ggplot(circle, aes(x, y)) +
  geom_path() + 
  coord_fixed() +  # Ensures the aspect ratio is 1:1
  theme_minimal()
```




```{r}
library(plotrix)  # Make sure plotrix is loaded

x = runif(100, -1, 1)  # Generate random x coordinates
y = runif(100, -1, 1)  # Generate random y coordinates

plot(x, y, asp = 1, xlim = c(-1, 1), ylim = c(-1, 1))  # Ensure correct aspect ratio
draw.circle(0, 0, 1, nv = 100)  # Draw the circle
```





```{r}
# load library tidyverse 
library(tidyverse) 
  
# create data for world coordinates using  
# map_data() function 
world_coordinates <- map_data("world") 
  
# create world map using ggplot() function 
ggplot() + 
  
# geom_map() function takes world coordinates  
# as input to plot world map 
  geom_map( 
    data = world_coordinates, map = world_coordinates, 
    aes(long, lat, map_id = region)) +
  labs(x = "dlugość", y = "szerokość") +
  theme_bw() +
 theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        # axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
```











```{r}

```

